### ISSUE TITLE
Doesnt work in ubuntu 18.04

### ISSUE THREAD

**Issue by ejgutierrez74** [redhat-developer/vscode-xml#291] opened 2020-07-16 17:14 UTC
It does nothing....

I have installed the latest version: https://github.com/redhat-developer/vscode-xml and does nothing
I have java home configured as environement variable: JAVA_HOME=/usr/lib/jvm/java-8-oracle

So it should work....

Ubuntu 18.04
VSCode latest version

![imagen](https://user-images.githubusercontent.com/11474846/87701567-7e87b200-c798-11ea-947e-86d24ecc1ce1.png)

**Comment by angelozerr** [comment] 2020-07-16 17:57
Could you try to force this Java hone with settings:

"xml.java.home": "/usr/lib/jvm/java-8-oracle"

or with 

"xml.java.home": "/usr/lib/jvm/java-8-oracle/bin"

**Comment by ejgutierrez74** [comment] 2020-07-18 15:34
Dont know how, but today worked ... i have reinstalled the plugin several times....exit vscode and launch again vscode, but didnt work... Suppose i had to reboot computer ( dont know why as all the plugins in vscode can be installed and uninstalled without rebooting computer...).

By the way it works both with oracle and openjdk java no ?

Thanks

**Comment by angelozerr** [comment] 2020-08-04 09:44
> Suppose i had to reboot computer

I suppose JAVA_HOME path environment has been done correctly?

> By the way it works both with oracle and openjdk java no ?

Yes it should work. We try to discover the Java Runtime path, but in some cases (which cases ?) we cannot find it. That's why we provide a settings `"xml.java.home": "/usr/lib/jvm/java-8-oracle"` which is used to use the given Java Runtime.

> Also seem that schema takes the xml order in alphapetical order and not in the order i want ( ex: root have square, instant, leg, recently, report and spent as sons... in this order... but in schema the order is changed and appears in alphabetical order as you can see in the picture:

I suppose you speak about outline. If it that you must configure sort by position:

![image](https://user-images.githubusercontent.com/1932211/89279291-7c9e6980-d647-11ea-9121-d001afc0fbd9.png)

> How can i "prettier" the code.. id like that tags where in blue or highlighted and the text inside in black....

Sorry I don't understand what you mean? You mean that Outline doesn't displays text node? If you need some new features please create a new issues by giving more description. Thanks.

I close this issue since you have fixed the original problem.

**Closed by angelozerr** 2020-08-04 09:44 UTC
Labels: invalid

**Comment by xorye** [comment] 2020-08-04 13:10
> How can i "prettier" the code.. id like that tags where in blue or highlighted and the text inside in black....

@angelozerr I think the problem is that there is no syntax highlighting in the xml file.

@ejgutierrez74 does the problem persist with other VS Code themes?

**Comment by angelozerr** [comment] 2020-08-04 13:15
> @angelozerr I think the problem is that there is no syntax highlighting in the xml file.

Oh right! That's very strange because XML syntax coloration is managed by vscode himself. If you uninstall vscode-cml from Red Hat, have you the same problem with syntax coloration?

**Comment by ejgutierrez74** [comment] 2020-08-05 16:17
@xorye  @angelozerr 
Sorry for my bad english....
the problem is syntax highlighting.... i use other vscode plugins like unity in ¢# and html, and sql... all have the highlighting quite well

Thanks for your help...

**Comment by angelozerr** [comment] 2020-08-05 17:21
> the problem is syntax highlighting..

vscode-xml doesn't manage syntax highlighting, it is managed with vscode himeslf. You could check that by uninstalling vscode-xml and if you have the problem again, it means that it's an another extension which causes the problem.

**Comment by ejgutierrez74** [comment] 2020-08-06 15:51
vscode-xml is the only extension that uses xml.... all the others use other languages as said before, SQL, C#, HTML...
Thanks

**Comment by angelozerr** [comment] 2020-08-06 16:53
> vscode-xml is the only extension that uses xml.... 

I understand, but syntax coloration is done by vscode, not by vscode-xml, so if you unistall vscode-xml you should have syntax coloration again. Have you the same problem if you uninstall vscode-xml ?
