### ISSUE TITLE
"Join CDATA Lines" option not working on Format

### ISSUE THREAD

**Issue by VeteraNovis** [redhat-developer/vscode-xml#719] opened 2022-06-09 08:58 UTC
I have built the extension VSIX from source, using the master branch for version `0.21.0` which includes the [new changes](https://github.com/redhat-developer/vscode-xml/pull/714) to show the closing tag on code folding. I'm interested in this feature to be able to more easily collapse and comment out large blocks of the XML. This new behaviour doesn't work however when nodes with CDATA are present with line breaks, causing the new lines within the CDATA tag to be completely un-indented.

I turned on the "Join CDATA Lines" option and attempted to format the XML, but the CDATA lines did not join.

I have confirmed that the formatter is working by removing some tabs from a line and watching the formatter fix the tab spacing, however nothing appears to work regarding CDATA line joining.

## Steps to reproduce

1. Clone vscode-xml repo using master branch
2. Run command `npm ci`
3. EDIT: See edit section below for missing step
4. Install `vsce` package if needed with `npm install --location=global vsce` (My version is 2.9.1)
5. Build package with command `vsce package` inside `vscode-xml` directory
6. Manually install package to VSCode using newly created VSIX file `vscode-xml-0.21.0.vsix`
7. Set `xml.format.joinCDATALines` equal to `true` in VS Code settings
8. Open an XML file containing CDATA tags spread across multiple lines
9. Use `Ctrl + Shift + P` and select `XML Tools: Format as XML`
10. Witness nothing change

EDIT:
I had run the `npm build-server` command after I had already packaged the vsix file (Thank you @fbricon). This ensured that the language server was working locally as expected, but did not resolve the inability to join CDATA lines.

## Settings

```json
    "xml.codeLens.enabled": true,
    "xml.format.joinCDATALines": true,
    "xml.format.joinContentLines": true,
    "xml.format.joinCommentLines": true,
    "xml.foldings.includeClosingTagInFold": true,
    "xml.trace.server": "verbose",
    "xml.symbols.maxItemsComputed": 10000,
    "xml.server.vmargs": "-Xmx1G",
    "xml.java.home": "/usr/lib/jvm/java-8-openjdk-amd64/bin/",
```

**Comment by fbricon** [comment] 2022-06-09 09:54
you need to clone lemminx first
between steps 2 and 3, run `npm run build-server`, so the vsix embeds it

**Comment by VeteraNovis** [comment] 2022-06-09 10:05
> you need to clone lemminx first between steps 2 and 3, run `npm run build-server`, so the vsix embeds it

Ah yep, that makes sense. Thank you for pointing me in the right direction.

This now enables me to display the closing tag of a collapsed section, which also spans across multiline / unindented tags as expected.

Interestingly, the "Join CDATA Lines" option still doesn't appear to work. I no longer need that option, due to the code collapsing working correctly when I packaged the server into the VSIX file, but I'm not sure why it wouldn't be formatting correctly regardless.

**Comment by fbricon** [comment] 2022-06-09 10:08
looks like a regression that managed to creep through our test suite. I'm sure @angelozerr will figure it out

**Comment by angelozerr** [comment] 2022-06-09 10:44
@VeteraNovis you mean that join cdata formatting worked in old version?

**Comment by JessicaJHee** [comment] 2022-09-14 18:11
This issue is fixed by enabling the experimental formatter. The current behaviour can be seen here: 
![Peek 2022-09-09 11-58](https://user-images.githubusercontent.com/73968480/190230647-ca2cd3b5-9d10-459f-8bb5-a45ca96fa74e.gif)

**Comment by angelozerr** [comment] 2022-09-21 06:40
@VeteraNovis could you give us an XML snippet which cannot format correctly please in order to we can try it with experimental formatter and check if it works correctly. Thanks!

**Closed** 2022-11-15 19:27 UTC
Labels: bug, formatting
