### ISSUE TITLE
Documentation in completion has monospace font

### ISSUE THREAD

**Issue by felixfbecker** [redhat-developer/vscode-xml#32] opened 2018-09-12 11:55 UTC
![image](https://user-images.githubusercontent.com/10532611/45423389-7d186a80-b693-11e8-908f-f6fc439d10a4.png)

In other languages, this is rendered in a normal font

**Comment by fbricon** [comment] 2018-09-18 18:46
Most likely caused by the server sending plain text doco. It should return markdown instead.

**Comment by angelozerr** [comment] 2018-09-20 12:42
> It should return markdown instead.

Please create an issur for that. But the main problem is that teh xsd:documentation can be written in any format (text, html, other). So how to convert any format to markdown?

**Comment by felixfbecker** [comment] 2018-09-20 12:43
Plain text renders fine as markdown. Markdown can include HTML, so HTML renders fine as markdown too. Are there any other formats used in the wild?

**Comment by angelozerr** [comment] 2018-09-20 12:47
@felixfbecker you mean that lsp4xml doesn't need to convert to a markdown format? Just set the the MarkupContent as "markdown" kind?

**Comment by felixfbecker** [comment] 2018-09-20 12:49
Yeah. That's what all language servers I know do

**Comment by fbricon** [comment] 2018-09-20 12:52
Vscode markdown renderer does not support HTML in markdown documentation. See https://github.com/Microsoft/vscode/issues/21141#issuecomment-281931804

**Comment by felixfbecker** [comment] 2018-09-20 12:58
But how would marking the content as markdown (which it technically is in that case) be any worse than marking it as plain text? In both cases you see HTML tags in VS Code, but text _without_ HTML renders way nicer and other clients do not have this problem. Also, the hovers already seem to use markdown anyway?

**Comment by fbricon** [comment] 2018-12-05 19:04
Related server side issue: https://github.com/angelozerr/lsp4xml/issues/245

**Comment by fbricon** [comment] 2018-12-14 21:06
I quickly tried markdown rendering with remark: https://github.com/fbricon/lsp4xml/tree/remark:

<img width="529" alt="screen shot 2018-12-14 at 4 02 11 pm" src="https://user-images.githubusercontent.com/148698/50027419-2b48ee80-ffba-11e8-98b6-40a2ea24a89a.png">

**Comment by fbricon** [comment] 2019-07-04 15:33
@angelozerr we have Markdown support on hover now but not for completion. Should be pretty straightforward to add

**Comment by angelozerr** [comment] 2019-07-04 16:11
> @angelozerr we have Markdown support on hover now but not for completion. Should be pretty straightforward to add

Yes sure, we must just take care of documentationFormat coming from client capabilities:

```
"completion": {
...
                "completionItem": {
...
                  "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],

```

**Comment by fbricon** [comment] 2019-07-22 21:17
Fixed with https://github.com/angelozerr/lsp4xml/pull/528

**Closed by fbricon** 2019-07-22 21:17 UTC
Labels: enhancement

**Comment by fbricon** [comment] 2019-07-22 21:20
Also includes link to (local cache of) schema:
![hoverandcompletionmarkdownsupport](https://user-images.githubusercontent.com/148698/61666192-2c23ca80-acd7-11e9-900d-6571fcc4e4ce.gif)
