### ISSUE TITLE
The formatter doesn't seem to use the VSCode proxy for downloading xsd files

### ISSUE THREAD

**Issue by halloleo** [redhat-developer/vscode-xml#735] opened 2022-07-13 04:04 UTC
When the extension formats a pom.xml (which contains an XML Schema) VS Code issues the problem "_Error while downloading 'http://maven.apache.org/xsd/maven-4.0.0.xsd'..._".

I have defined a proxy in VS Code's settings, but I assume the extension does not obey/use this proxy.

Is there another way to tell the formatter to use a proxy?

**Comment by fbricon** [comment] 2022-07-13 06:55
Please see if https://github.com/redhat-developer/vscode-xml/blob/master/docs/Proxy.md helps

**Comment by halloleo** [comment] 2022-07-13 07:10
Thanks @fbricon ! 

I have set `http.proxy` in vscode's settings.  I don't need authorisation.

I left `http.proxySupport` alone, showing "override" in the dialog.

This is from my understanding exactly what the page you link to says - but it doesn't work.

PS: On the page is the strange sentence: "*If you set [http.proxySupport] to override, VS Code will attempt to rewrite the requests from extensions to go through the proxy that is configured for VS Code. **However, this method sometimes does not work correctly.***" - In my case it doesn't seem to work correctly indeed, so what can I do?

**Comment by fbricon** [comment] 2022-07-13 07:26
@datho7561 can you please investigate?

**Comment by datho7561** [comment] 2022-07-13 17:39
Hello! I've tried on my machine with [this proxy](https://hub.docker.com/r/ubuntu/squid), and everything appears to be working. 

Which version of the extension are you using? Which version of VS Code (/Codium/Theia/?) are you using?

One thing that might be related is that http://maven.apache.org/xsd/maven-4.0.0.xsd redirects to the https version of the website; maybe something goes wrong when trying to handle this redirect? I'll research some more.

**Comment by halloleo** [comment] 2022-07-14 06:34
Just FYI: When I do 

    wget http://maven.apache.org/xsd/maven-4.0.0.xsd

with the px-proxy entered in my `.wgetrc`, hen I can download the schema without problems.

**Comment by datho7561** [comment] 2022-07-14 18:13
I was able to get a proper setup where my machine needs to use the proxy to access the http/https, and I am able to reproduce the issue.

**Comment by datho7561** [comment] 2022-07-14 19:31
I figured out the issue and am working on the PR. In the mean time, here is a workaround: https://github.com/redhat-developer/vscode-xml/blob/master/docs/Preferences.md#server-vm-arguments. My PR will just make sure that these parameters are set for you if you have set `http.proxy` in the VS Code settings.

**Comment by halloleo** [comment] 2022-07-15 01:33
Thanks that you looked into this! :)

**Comment by datho7561** [comment] 2022-09-21 11:14
@angelozerr It should be fixed in the prereleases, but we haven't released since then

**Comment by angelozerr** [comment] 2022-11-15 19:24
@datho7561 I think we can close this issue no?

**Closed** 2022-11-15 19:28 UTC
Labels: bug
