### ISSUE TITLE
No way to clear loaded XSD cache - a trouble when developing schemas

### ISSUE THREAD

**Issue by vukovinski** [redhat-developer/vscode-xml#319] opened 2020-09-01 13:29 UTC
Currently the retrieved schema definition file gets stored somewhere and cannot be deleted even after extension uninstall/reinstall.

Would like a command to manually re-retrieve the schema files for the current XML file.

**Comment by vukovinski** [comment] 2020-09-01 13:34
Did manage to find the .lemminx folder in my user directory, and the cache was exactly there! ❤

**Comment by fbricon** [comment] 2020-09-01 13:44
We could expose a command to open the cache directory, but that would only concern a minority of users, not sure it's worth it as I don't want to bloat the actions list if we can avoid it. 
However we should definitely better document the caching mechanism.

**Comment by vukovinski** [comment] 2020-09-01 15:54
What about writing the location of the cache folder to the integrated output on init?

**Comment by fbricon** [comment] 2020-09-01 17:26
sure we could do that. For now you have logs about downloaded schemas like:

```
[Info  - 7:19:54 PM] Sep. 01, 2020 07:19:54 org.eclipse.lemminx.uriresolver.CacheResourcesManager lambda$downloadResource$0()
Message: Downloading https://testng.org/testng-1.0.dtd to /Users/fbricon/.lemminx/cache/https/testng.org/testng-1.0.dtd...
[Info  - 7:19:55 PM] Sep. 01, 2020 07:19:55 org.eclipse.lemminx.uriresolver.CacheResourcesManager lambda$downloadResource$0()
Message: Downloaded https://testng.org/testng-1.0.dtd to /Users/fbricon/.lemminx/cache/https/testng.org/testng-1.0.dtd in 785ms
```

**Comment by vukovinski** [comment] 2020-09-02 08:58
I believe that your first suggestion on enhancing documentation is probably the best way to solve this UX issue.

How about an option to re-download the schema on save?

**Comment by fbricon** [comment] 2020-09-02 09:01
that's equivalent to disabling caching, which would dramatically impact the performance, as the schema resolution is done several times per server query

**Comment by fbricon** [comment] 2020-09-02 09:04
maybe exposing a command to force schema refresh, triggered on demand might do it

**Comment by vukovinski** [comment] 2020-09-02 11:44
Sure, makes sense.

**Comment by angelozerr** [comment] 2020-09-16 08:39
@vukovinski  could you explain please your usecase? If you are writting XSD and you change it, your XSD is on local, so you should not having the cache problem.

If you use remote XSD file (have you an URL for this XSD file), those XSD should not change every time, no? Removing at hand the cache is not a big deal I think.

But an idea that I had is to check the get last modified of the XSD URL to know if the XSD file must be downloaded or not. It means that an URL connection will be created each time the XML file must be validated, but we could enable/disable this feature with settings (ex : `xml.validation.checkLastModifed`).

**Comment by angelozerr** [comment] 2020-09-16 08:50
@fbricon I think we have the same idea https://github.com/redhat-developer/vscode-xml/issues/284#issuecomment-651635729

**Comment by angelozerr** [comment] 2020-10-15 10:34
This issue is a duplicate of https://github.com/redhat-developer/vscode-xml/issues/284

@vukovinski please note that I'm working on this issue, see demo at https://github.com/redhat-developer/vscode-xml/pull/343#issuecomment-709120128

**Closed by angelozerr** 2020-10-15 10:34 UTC
Labels: duplicate
