### ISSUE TITLE
Is there a way to associate XML files by file name pattern to XSD schema locations?

### ISSUE THREAD

**Issue by felixfbecker** [redhat-developer/vscode-xml#25] opened 2018-09-11 09:29 UTC
I would like to register the same schemas be used for all `*.xsd` and `*.Format.ps1xml` files. Is there a way to do that through a setting?

**Comment by fbricon** [comment] 2018-09-11 12:44
Closing as duplicate of #17

**Closed by fbricon** 2018-09-11 12:44 UTC
Labels: duplicate
