### ISSUE TITLE
Set "xml.format.enforceQuoteStyle"="ignore" by default

### ISSUE THREAD

**Issue by bduffany** [redhat-developer/vscode-xml#263] opened 2020-05-22 18:00 UTC
## Input (valid XML)
```xml
<foo bar='Hello "world"!' />
```

## Formatted output (with `doubleQuotes` preference -- produces invalid XML)
```xml
<foo bar="Hello "world"!" />
```

## Expected output (valid XML -- quotes preference should be ignored in favor of keeping the XML valid)
```xml
<foo bar='Hello "world"!' />
```

**Comment by fbricon** [comment] 2020-05-22 18:02
Closing as duplicate of #182

**Comment by bduffany** [comment] 2020-05-22 18:06
Thanks Fred! Just to provide some additional feedback, it is a _really_ bad developer experience if I have to manually set a preference ("xml.format.enforceQuoteStyle"="ignore") in order for an extension to not be buggy after installing it. Y'all should really consider making that option enabled by default.

**Comment by fbricon** [comment] 2020-05-23 15:58
I agree that the default behavior should be the safest. We can certainly disable quote formatting by default, until it's made more robust.

**Comment by fbricon** [comment] 2020-05-25 15:14
@datho7561 FYI, these are the required changes:
- https://github.com/redhat-developer/vscode-xml/commit/35d4af9a41d67cb9461904b4282d00ec08fe65f9#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R184
- README.md should indicate it's disabled by default

On the server side:
- https://github.com/eclipse/lemminx/blob/acaa560a2ebac52cc2edf6d1aa235f4b38b1dfce/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/settings/XMLFormattingOptions.java#L28

makes sure server tests pass and show that ignore is used by default

**Closed** 2020-05-27 13:34 UTC
Labels: formatting
