### ISSUE TITLE
Extension is not running and validating .xml file

### ISSUE THREAD

**Issue by MarcelGeo** [redhat-developer/vscode-xml#856] opened 2023-01-12 12:17 UTC
VSCODE:
version: 1.74.2
EXTENSION:
version: 0.23.0

Error:

[Error - 13:01:35] jan 12, 2023 01:01:35 org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError()
Message: Missing header Content-Length in input "{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///c%3A/Users/marcel.kocisek/OneDrive%20-%20stengl%20a.s/Documents/Reporting2018/fhrm.xml","version":6},"contentChanges":[{"range":{"start":{"line":4,"character":20},"end":{"line":5,"character":4}},"rangeLength":6,"text":""}]}}Content-Length: 180

"
java.lang.IllegalStateException: Missing header Content-Length in input "{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///c%3A/Users/marcel.kocisek/OneDrive%20-%20stengl%20a.s/Documents/Reporting2018/fhrm.xml","version":6},"contentChanges":[{"range":{"start":{"line":4,"character":20},"end":{"line":5,"character":4}},"rangeLength":6,"text":""}]}}Content-Length: 180

"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

File:
```
http<?xml version="1.0" encoding="utf-8"?>
<?xml-model href="https://dd.eionet.europa.eu/schemas/Floods/" type="application/xml"?>
<?xml-model href="https://dd.eionet.europa.eu/schemas/Floods/FHRM.xsd" type="application/xml"?>
<FHRM xmlns="http://dd.eionet.europa.eu/schemas/Floods" xmlns:fd="http://dd.eionet.europa.eu/schemas/Floods/FDcommon" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://dd.eionet.europa.eu/schemas/Floods/ https://dd.eionet.europa.eu/schemas/Floods/FHRM.xsd" CreationDate="2014-02-14" Creator="Slovak Water Management Enterpise, state owned" Email="mpomprsr@svp.sk" Language="sk" Description="Slovenský vodohospodársky podnik">
    <hejno>d</hejno>
</FHRM>
```

**Comment by angelozerr** [comment] 2023-01-13 07:47
I cannot reproduce it It seems that it is a problem from https://github.com/eclipse/lsp4j

We need to investigate how we can reproduce this issue.

**Comment by MarcelGeo** [comment] 2023-01-13 11:00
We could make video call ?

**Comment by angelozerr** [comment] 2023-01-13 12:20
Could you share your xml trace please. See https://github.com/redhat-developer/vscode-xml/blob/main/docs/Troubleshooting.md#no-support-on-xml-file

**Comment by angelozerr** [comment] 2023-01-13 12:22
I don't know if it is related to your path `file:///c%3A/Users/marcel.kocisek/OneDrive%20-%20stengl%20a.s/Documents/Reporting2018/fhrm.xml`

Could you please copy/paste your `fhrm.xml` in your C folder directory and open it. Is it working better?

**Comment by rgrunber** [comment] 2023-01-13 14:33
Assuming you're able to hit this issue consistently, @MarcelGeo , can you try the following to see if it resolves the issue :

Under settings, for `xml.server.vmargs`, set the following value : `-Xmx64M -Xlog:disable` . If you already use your own custom setting there, just add `-Xlog:disable` to the end. Let us know if that fixes anything.

**Comment by MarcelGeo** [comment] 2023-01-13 16:29
Thanks for answers. I will try it on monday.

**Comment by MarcelGeo** [comment] 2023-01-16 07:57
@angelozerr Moving file to C caused the same error:

[Error - 8:51:19] jan 16, 2023 08:51:19 org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError()
Message: Missing header Content-Length in input "{"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///c%3A/fhrm.xml"}}}Content-Length: 107

"
java.lang.IllegalStateException: Missing header Content-Length in input "{"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///c%3A/fhrm.xml"}}}Content-Length: 107

"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

@rgrunber The same error after changing vmargs to: "xml.server.vmargs": "-Xmx128M -Xlog:disable"

This is initial log for XML extension after open first XML file (maybe this will be problem):

[Info  - 8:56:08] jan 16, 2023 08:56:08 org.eclipse.lemminx.XMLLanguageServer initialize()
Message: Initializing XML Language server
LemMinX Server info:
 - Version : 0.23.2
 - Java : C:\PROGRA~1\ADOPTO~1\JDK-11~1.10-
 - VM Version : 11.0.8
 - Git b699556 - [maven-release-plugin] prepare release 0.23.2
[Error - 8:56:08] jan 16, 2023 08:56:08 org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError()
Message: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:1226)
	at com.google.gson.Gson.fromJson(Gson.java:1173)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:119)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:92)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:55)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	... 11 more

**Comment by angelozerr** [comment] 2023-01-16 08:14
Could you try to force use of binary with adding in your settings.json `"xml.server.preferBinary": true`

**Comment by MarcelGeo** [comment] 2023-01-16 11:46
![image](https://user-images.githubusercontent.com/12643115/212671104-686922ab-48d4-4873-bf29-4d24f63eaa6c.png)
The same issue with this option enabled.

**Comment by angelozerr** [comment] 2023-01-16 17:59
Could you share your trace server please by activating binary. Thanks

**Comment by angelozerr** [comment] 2023-01-16 18:01
Could you share your settings.json please. Thanks

**Comment by angelozerr** [comment] 2023-01-16 18:04
Could you create a simple xml like

<foo

It should show you an error.

**Comment by rgrunber** [comment] 2023-01-16 18:33
One thing I noticed is that your `Content-Length` header is coming after the content part of the message. This definitely doesn't seem right. According to https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#baseProtocol, it should be coming before.

@angelozerr seems this is kind of similar to https://github.com/eclipse/lsp4j/issues/616 ?

**Comment by MarcelGeo** [comment] 2023-01-17 13:41
Hi guys.

I dont now. After update VSCode to version 1.74.3 problem is **NOT OCCURED** . Sorry for your time.

**Comment by angelozerr** [comment] 2023-01-17 14:50
Hi @MarcelGeo 

Glad to see that your issue is fixed now by updating vscode. I suspect that it was problem with encoding, but now if it is working, that's great.

Hope you will enjoy with vscode-xml.

**Closed by angelozerr** 2023-01-17 14:50 UTC

**Comment by rgrunber** [comment] 2023-01-17 15:34
I'm not really seeing anything in https://github.com/microsoft/vscode/compare/1.74.2...1.74.3 that would have fixed this :\ but perhaps it's some kind of encoding issue on the client side ? Also see https://github.com/microsoft/vscode-languageserver-node/issues/917 .
