### ISSUE TITLE
Hover error 

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-xml#43] opened 2018-09-20 17:40 UTC
When I hover on a pom.xml I see the hover content as `Unsupported Markup content received. Kind is: undefined`.

**Comment by fbricon** [comment] 2018-09-21 15:41
@angelozerr error still occurs. Server sends:
```
[Trace - 11:37:47 AM] Received response 'textDocument/hover - (13)' in 3ms.
Result: {
    "contents": {
        "value": "The modules (sometimes called subprojects) to build as a part of this project. Each module listed is a relative path to the directory containing the module. To be consistent with the way default urls are calculated from parent, it is recommended to have module names match artifact ids."
    }
}

```

**Comment by angelozerr** [comment] 2018-09-22 13:06
I will investigate more, but the thing I don't understand is that it worked before, now? Perhaps you are using last version of vscode which breaks something.

**Comment by angelozerr** [comment] 2018-09-22 13:11
It works for me?

![image](https://user-images.githubusercontent.com/1932211/45917541-bb730e00-be79-11e8-8667-05329d528a06.png)

**Comment by fbricon** [comment] 2018-09-23 21:35
I can no longer reproduce the issue. Closing as fixed.

**Closed by fbricon** 2018-09-23 21:35 UTC
Labels: bug, hover, to do
