### ISSUE TITLE
Error logged when opening maven-4.0.0.xsd on Windows

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#408] opened 2021-02-03 10:12 UTC
On Windows 10, with vscode-xml 0.15.0-108, using the xml binary, after opening a pom.xml then opening the maven-4.0.0.xsd link from the doc on hover, I got this error logged several times in the xml output:

```
[Error - 11:03:04] Feb 03, 2021 11:03:04 org.eclipse.lemminx.utils.FilesUtils saveToFile()
Message: The associated file system 'C:\Users\Zachary\.lemminx\cache\http\www.w3.org\2001\XMLSchema.dtd' + does not support the PosixFileAttributeView
java.lang.UnsupportedOperationException
	at java.nio.file.Files.setPosixFilePermissions(Files.java:2078)
	at org.eclipse.lemminx.utils.FilesUtils.saveToFile(FilesUtils.java:155)
	at org.eclipse.lemminx.utils.FilesUtils.saveToFile(FilesUtils.java:135)
	at org.eclipse.lemminx.uriresolver.CacheResourcesManager.getResourceCachePath(CacheResourcesManager.java:243)
	at org.eclipse.lemminx.extensions.xsd.XSDURIResolverExtension.resolve(XSDURIResolverExtension.java:65)
	at org.eclipse.lemminx.uriresolver.URIResolverExtensionManager.resolveInfo(URIResolverExtensionManager.java:108)
	at org.eclipse.lemminx.extensions.contentmodel.model.ContentModelManager.fillReferencedGrammarInfo(ContentModelManager.java:235)
	at org.eclipse.lemminx.extensions.contentmodel.model.ContentModelManager.getReferencedGrammarInfos(ContentModelManager.java:229)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelSymbolsProviderParticipant.findDocumentSymbols(ContentModelSymbolsProviderParticipant.java:72)
	at org.eclipse.lemminx.services.XMLSymbolsProvider.processSymbolsParticipants(XMLSymbolsProvider.java:402)
	at org.eclipse.lemminx.services.XMLSymbolsProvider.findDocumentSymbols(XMLSymbolsProvider.java:166)
	at org.eclipse.lemminx.services.XMLLanguageService.findDocumentSymbols(XMLLanguageService.java:138)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$documentSymbol$7(XMLTextDocumentService.java:270)
	at java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	at java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
```

**Comment by fbricon** [comment] 2021-02-03 10:14
See https://stackoverflow.com/a/14415997

**Comment by datho7561** [comment] 2021-02-03 15:23
I can't reproduce this with 0.15.0-108 running the binary and using the child pom.xml for LemMinX copied to a separate directory. What is the commit hash of the server?

**Comment by angelozerr** [comment] 2021-05-26 09:28
Duplicate of https://github.com/eclipse/lemminx/issues/734

**Closed by angelozerr** 2021-05-26 09:28 UTC
Labels: bug
