### ISSUE TITLE
100% CPU load 

### ISSUE THREAD

**Issue by antirius** [redhat-developer/vscode-xml#387] opened 2020-12-23 14:02 UTC
100% CPU utilization in large projects .. In which there is no XML!

**Comment by antirius** [comment] 2020-12-23 14:02
MacOS

**Comment by angelozerr** [comment] 2020-12-23 14:36
That's very strange because the XML Language server is started only when a XML file is opened. Could you share your project or provide a similar project which causes this problem. Thanks.

**Comment by antirius** [comment] 2020-12-23 15:14
Apparently the problem is that an xml file was opened in one of the windows. At the same time, several copies of VS Code were launched (4 copies, each containing 3-15 project directories).
Does he start scanning everything not only in the current project?
![img-2020-12-23-18-13-14](https://user-images.githubusercontent.com/11909819/103011288-b9adbe80-454a-11eb-8ddd-4b4934596e9e.png)

**Comment by angelozerr** [comment] 2020-12-23 15:17
Could you share your project please?

**Comment by antirius** [comment] 2020-12-23 15:21
Unfortunately not. The only thing I can say is that there are a lot of files. Plus these are nodejs projects, and there are even more dependencies in node_modules.

**Comment by angelozerr** [comment] 2020-12-23 15:27
It's very hard to help you without a project which causes your issue.

Could you add in your settings.json add `"xml.trace.server": "verbose"` and and share the XML support Output 
![image](https://user-images.githubusercontent.com/1932211/103012318-b6f79d00-453b-11eb-87e9-13ae6d463ca6.png)

when your issue will come back.

**Comment by antirius** [comment] 2020-12-23 15:35
To understand what is slowing down, I had to kill java (delete from disk), and then the XML extension error got out)
Next time I install it, I will definitely try the tracing and drop the log, thanks!)

**Comment by rgrunber** [comment] 2022-07-20 00:34
Is this still reproducible in the latest vscode-xml ?

The 100% cpu load seems similar to https://github.com/eclipse/lemminx/issues/1175 . It happened when `"xml.validation.enabled` was set to `false`. In addition, we have made a lot of performance improvements in the [0.21.0 release](https://github.com/redhat-developer/vscode-xml/blob/master/CHANGELOG.md#performance)

**Comment by rgrunber** [comment] 2022-09-19 13:54
Closing this issue as I suspect it was fixed some time ago. Feel free to re-open if it persists.

**Closed by rgrunber** 2022-09-19 13:54 UTC
Labels: performance, need info
