### ISSUE TITLE
XSD with enumeration restriction with 1000+ entries fail type assist

### ISSUE THREAD

**Issue by lunarwtr** [redhat-developer/vscode-xml#679] opened 2022-03-21 14:27 UTC
If I create an XSD with enumeration restriction with 1000+ entries.  Then go to use that schema on xml file.. The autocomplete gets stuck at "Loading ..." forever.

**Comment by lunarwtr** [comment] 2022-03-21 16:21
Bug occurs when it is like this..
![image](https://user-images.githubusercontent.com/9368775/159304910-ea97fdab-20af-4662-8e4e-299321de800d.png)

If you let autocomplete happen on attribute ArtAssetI...  it then works
![image](https://user-images.githubusercontent.com/9368775/159305088-9af456dc-d727-4bbf-83e9-9ca8cd0cb9ad.png)

**Comment by lunarwtr** [comment] 2022-03-21 16:22
[example.zip](https://github.com/redhat-developer/vscode-xml/files/8317207/example.zip)

attaching sample project

**Comment by fbricon** [comment] 2022-03-21 16:24
@lunarwtr the interesting part is your xsd with 1000+ enum, that we need to understand the issue

**Comment by lunarwtr** [comment] 2022-03-21 16:36
I want to provide restriction on the values for that attribute. There is a limited set. 

What interesting is it instantly Loads the enumeration if I select autocomplete (before it gets to equal sign)..

![image](https://user-images.githubusercontent.com/9368775/159310614-2b6ed131-7136-446e-bf6f-a77da2f3eba7.png)

**Comment by fbricon** [comment] 2022-03-21 18:06
sure, now if you could please attach your xsd, that'd help

**Comment by angelozerr** [comment] 2022-03-21 18:46
@fbricon the XSD is included inside th eexample.zip. I can reproduce it.

The main problem is that completion takes too many times to compute list of enumeration with text edit. A possible solution should be support completion/resolve and compte the textedit only if needed.

**Comment by angelozerr** [comment] 2022-03-21 18:51
> What interesting is it instantly Loads the enumeration if I select autocomplete (before it gets to equal sign)..

Thanks for the feedback, I think it's because the JSON response from completion contains documentation and textedit which is a very big JSON. compeltion/resolve could be a solution.

**Comment by lunarwtr** [comment] 2022-03-21 19:15
thank you @angelozerr

**Comment by angelozerr** [comment] 2022-06-27 07:07
@lunarwtr completion resolve has been implemented and it should fix your issue, see https://github.com/eclipse/lemminx/pull/1234#issuecomment-1166963045

**Comment by angelozerr** [comment] 2022-06-29 07:03
Fixed with https://github.com/eclipse/lemminx/pull/1234

**Closed by angelozerr** 2022-06-29 07:03 UTC
