### ISSUE TITLE
XML Support client: couldn't create connection to server.

### ISSUE THREAD

**Issue by NagarjunaParala** [redhat-developer/vscode-xml#880] opened 2023-02-24 06:57 UTC
XML Support client: couldn't create connection to server.

**Comment by angelozerr** [comment] 2023-02-24 07:27
You can try setting `"xml.server.vmargs": "-Xmx64M -Xlog:disable"` if Java is used to run the language server, or set `"xml.server.preferBinary": true`, so it doesn't use the JVM

**Comment by Tazaf** [comment] 2024-03-21 09:18
If you are on a Mac with an Apple processor, you should try and install Rosetta2 with `softwareupdate --install-rosetta`.

The README of the extension specifically says that there is no binary available for Apple processor, but that it works with Rosetta2, and I can confirm that it does.

**Comment by fbricon** [comment] 2024-03-21 09:32
Please try pre-releases, where Apple M* processors now have proper binary. See https://github.com/redhat-developer/vscode-xml/issues/898#issuecomment-1919800217

**Comment by jasonlyle88** [comment] 2024-05-31 12:32
I am on a mac with an intel processor and I am getting the same error message. I have tried with all default settings, with setting just the `xml.server.vmargs`, with setting the`xml.server.preferBinary`, and also setting both `xml.server.vmargs` and `xml.server.preferBinary` to the values mentioned above. All of the combinations still yielded the same error popup.

The error popup does have a `Go to output` button, and I noticed two different sets of error messages.

If I opened VS Code without any XML file open, then open an XML file, the output would be the following error message:
```
XML Support client: couldn't create connection to server.
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:414:11)
    at Object.spawn (node:child_process:799:9)
    at transports (/Users/jlyle/.vscode/extensions/redhat.vscode-xml-0.27.0-darwin-x64/node_modules/vscode-languageclient/lib/node/main.js:424:46)
    at x.connection [as createConnection] (/Users/jlyle/.vscode/extensions/redhat.vscode-xml-0.27.0-darwin-x64/node_modules/vscode-languageclient/lib/common/client.js:1030:15)
    at x.start (/Users/jlyle/.vscode/extensions/redhat.vscode-xml-0.27.0-darwin-x64/node_modules/vscode-languageclient/lib/common/client.js:612:19)
```

If I opened VS code with an XML file already open, the output would be the following error message:
```
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:414:11)
    at Object.spawn (node:child_process:799:9)
    at /Users/jlyle/.vscode/extensions/redhat.vscode-xml-0.27.0-darwin-x64/dist/extension.js:2:552400
    at async x.createConnection (/Users/jlyle/.vscode/extensions/redhat.vscode-xml-0.27.0-darwin-x64/dist/extension.js:2:391359)
    at async x.start (/Users/jlyle/.vscode/extensions/redhat.vscode-xml-0.27.0-darwin-x64/dist/extension.js:2:382808)
```

So the settings changes did nothing to effect the error message or output, but when the XML file was opened did change the output.

**Comment by jasonlyle88** [comment] 2024-05-31 12:41
Okay, just realized I missed resetting one of my settings to its default value. My `xml.java.home` was set to an invalid value. As soon as I cleared out that setting, everything worked fine. @NagarjunaParala , you may want to check which settings you have set for this extension, specifically if you have an `xml.java.home` set that is invalid.

Leaving my previous post about the errors I was getting in case it is helpful to the development team to create a more robust handler/better error messaging for when an invalid java home is detected!

**Comment by fbricon** [comment] 2024-05-31 12:54
@jasonlyle88  vscode-xml 0.27.1 is out with a fix for your issue

**Comment by jasonlyle88** [comment] 2024-05-31 13:00
@fbricon I just upgraded and added an invalid java home back to my settings. The extension did indeed fall back to the binary gracefully! Thanks!

**Comment by angelozerr** [comment] 2024-08-25 10:38
It seems the issue is fixed.

I close the issue. @NagarjunaParala if it doesn't work for you, please reopen it.

**Closed by angelozerr** 2024-08-25 10:38 UTC
Labels: bug
